In [112]:
!pip install keras

In [113]:
!pip install tensorflow

In [115]:
!pip install keras-preprocessing


In [124]:
import tensorflow as tf
print(tf.__version__)


2.18.0


In [126]:
from tensorflow.keras.preprocessing.text import Tokenizer


In [128]:
pip install tensorflow --upgrade


In [130]:
!pip install keras-preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer


In [132]:
import pickle 
import numpy as np 
from keras.models import Sequential, Model 
from tensorflow.keras.layers import Embedding 
from keras.layers import Input, Activation, Dense, Permute, Dropout, add, dot, concatenate, LSTM 
from keras.preprocessing.sequence import pad_sequences  
from keras_preprocessing.text import Tokenizer

In [134]:
with open('C:\\Users\\hp\\Downloads\\train_qa.txt', 'rb') as f:
    train_data = pickle.load(f)
with open('C:\\Users\\hp\\Downloads\\test_qa.txt', 'rb') as f:
    test_data = pickle.load(f)


In [136]:
type(test_data)

list

In [138]:
type(train_data)

list

In [140]:
len(test_data)

1000

In [142]:
print(type(train_data))
print(type(test_data))

<class 'list'>
<class 'list'>


In [144]:
train_data[0]

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [146]:
train_data[0][1]

['Is', 'Sandra', 'in', 'the', 'hallway', '?']

In [148]:
train_data[0][0]

['Mary',
 'moved',
 'to',
 'the',
 'bathroom',
 '.',
 'Sandra',
 'journeyed',
 'to',
 'the',
 'bedroom',
 '.']

In [236]:
train_data[0][2]

'no'

In [238]:
all_data = test_data + train_data

In [240]:
len(all_data)

11000

In [242]:
vocab = set()

for story, question, answer in all_data:
    vocab = vocab.union(set(story))
    vocab = vocab.union(set(question))

In [244]:
vocab.add('no')

In [246]:
vocab.add('yes')

In [248]:
vocab_len=len(vocab)+1

In [250]:
vocab_len

38

In [252]:
# Length of all the stories
all_story_len = [len(data[0]) for data in all_data]

In [254]:
# Get maximum of the stories
max_story_len = max(all_story_len)

In [256]:

max_story_len 

156

In [258]:
max_question_len = max([len(data[1]) for data in all_data])

In [260]:
max_question_len

6

In [262]:
tokenizer = Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

In [272]:
tokenizer.word_index

{'moved': 1,
 '?': 2,
 'garden': 3,
 'is': 4,
 'got': 5,
 'dropped': 6,
 'to': 7,
 'the': 8,
 'sandra': 9,
 'back': 10,
 'kitchen': 11,
 'bedroom': 12,
 'went': 13,
 'there': 14,
 'john': 15,
 'up': 16,
 'football': 17,
 'left': 18,
 'travelled': 19,
 'took': 20,
 'hallway': 21,
 'mary': 22,
 'picked': 23,
 'journeyed': 24,
 'apple': 25,
 'in': 26,
 'bathroom': 27,
 'daniel': 28,
 'discarded': 29,
 'yes': 30,
 'grabbed': 31,
 'office': 32,
 '.': 33,
 'put': 34,
 'milk': 35,
 'no': 36,
 'down': 37}

In [274]:
train_story_text = []
train_question_text = []
train_answers = []

In [276]:
train_story_seq= tokenizer.texts_to_sequences(train_story_text)

In [338]:
len(train_story_seq)

10000

In [194]:
print(train_data[:2])  # Check first two entries


[(['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.'], ['Is', 'Sandra', 'in', 'the', 'hallway', '?'], 'no'), (['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.'], ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'], 'no')]


In [198]:
print("Length of train_data:", len(train_data))
print("First 2 items of train_data:", train_data[:2])



Length of train_data: 10000
First 2 items of train_data: [(['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.'], ['Is', 'Sandra', 'in', 'the', 'hallway', '?'], 'no'), (['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.'], ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'], 'no')]


In [200]:
train_story_text = []
train_question_text = []
train_answers = []

for i, (story, question, answer) in enumerate(train_data):
    if i < 5:  # Print only the first few iterations
        print(f"Processing item {i+1}:")
        print("Story:", story)
        print("Question:", question)
        print("Answer:", answer)
        
    train_story_text.append(story)
    train_question_text.append(question)
    train_answers.append(answer)

print("Final train_story_text length:", len(train_story_text))  # Should be 10,000
print("First 2 stories:", train_story_text[:2])


Processing item 1:
Story: ['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.']
Question: ['Is', 'Sandra', 'in', 'the', 'hallway', '?']
Answer: no
Processing item 2:
Story: ['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.']
Question: ['Is', 'Daniel', 'in', 'the', 'bathroom', '?']
Answer: no
Processing item 3:
Story: ['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.', 'Sandra', 'went', 'to', 'the', 'kitchen', '.', 'Daniel', 'went', 'back', 'to', 'the', 'bathroom', '.']
Question: ['Is', 'Daniel', 'in', 'the', 'office', '?']
Answer: no
Processing item 4:
Story: ['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to',

In [202]:
print("Before potential overwrite:", train_story_text[:2])
# Look for something like: train_story_text = []  # This would reset it


Before potential overwrite: [['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.'], ['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.']]


In [204]:
# Train_story_text is a list of lists of words
train_story_text[:2]

[['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'hallway',
  '.']]

In [284]:
from tensorflow.keras.preprocessing.text import Tokenizer

# Initialize the tokenizer
tokenizer = Tokenizer()

# Fit the tokenizer on the training data
tokenizer.fit_on_texts(train_story_text)

# Now convert texts to sequences
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

print(len(train_story_seq))  # Should print the correct length, like 1000


10000


In [336]:
print(len(train_data))  # Should be around 1000
print(train_data[:5])   # Print first 5 items in train_data


10000
[(['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.'], ['Is', 'Sandra', 'in', 'the', 'hallway', '?'], 'no'), (['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.'], ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'], 'no'), (['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.', 'Sandra', 'went', 'to', 'the', 'kitchen', '.', 'Daniel', 'went', 'back', 'to', 'the', 'bathroom', '.'], ['Is', 'Daniel', 'in', 'the', 'office', '?'], 'no'), (['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.

In [334]:
# Check if train_data is properly populated
print(f"Number of stories in train_data: {len(train_data)}")
print(f"First 2 stories in train_data: {train_data[:2]}")


Number of stories in train_data: 10000
First 2 stories in train_data: [(['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.'], ['Is', 'Sandra', 'in', 'the', 'hallway', '?'], 'no'), (['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.'], ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'], 'no')]


In [278]:
# Initialize the lists
train_story_text = []
train_question_text = []
train_answers = []

# Check if train_data is being accessed correctly
print(f"Total entries in train_data: {len(train_data)}")

for idx, (story, question, answer) in enumerate(train_data):
    train_story_text.append(story)
    train_question_text.append(question)
    train_answers.append(answer)

    # Check first few entries to ensure appending works
    if idx < 2:
        print(f"Story {idx}: {story}")
        print(f"Question {idx}: {question}")
        print(f"Answer {idx}: {answer}")

# After the loop, check the length
print(f"Length of train_story_text: {len(train_story_text)}")
print(f"First 2 stories in train_story_text: {train_story_text[:2]}")


Total entries in train_data: 10000
Story 0: ['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.']
Question 0: ['Is', 'Sandra', 'in', 'the', 'hallway', '?']
Answer 0: no
Story 1: ['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.']
Question 1: ['Is', 'Daniel', 'in', 'the', 'bathroom', '?']
Answer 1: no
Length of train_story_text: 10000
First 2 stories in train_story_text: [['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.'], ['Mary', 'moved', 'to', 'the', 'bathroom', '.', 'Sandra', 'journeyed', 'to', 'the', 'bedroom', '.', 'Mary', 'went', 'back', 'to', 'the', 'bedroom', '.', 'Daniel', 'went', 'back', 'to', 'the', 'hallway', '.']]


In [332]:
print(len(train_story_text))


10000


In [286]:
len(train_story_seq)

10000

In [340]:
train_story_seq[:2]

[[6, 12, 3, 1, 19, 2, 5, 10, 3, 1, 14, 2],
 [6,
  12,
  3,
  1,
  19,
  2,
  5,
  10,
  3,
  1,
  14,
  2,
  6,
  4,
  13,
  3,
  1,
  14,
  2,
  8,
  4,
  13,
  3,
  1,
  16,
  2]]

In [316]:
# Create our own list of list of word indicies with padding.
def vectorize_stories(data, word_index=tokenizer.word_index, max_story_len=max_story_len, max_question_len=max_question_len):
    # Stories = X
    X = []
    
    # Questions = Xq
    Xq = []
    
    # Y Correct Answer ['yes', 'no']
    Y = []
    for story, query, answer in data:
        
        # for each story
        # [23, 14, 15]
        x = [word_index[word.lower()] for word in story]
        xq = [word_index[word.lower()] for word in query]
        
        y = np.zeros(len(word_index)+1)
        y[word_index[answer]] = 1
        
        X.append(x)   # X holds list of lists of word indices for stories.
        Xq.append(xq) # Xq holds list of lists for word indices for questions.
        Y.append(y) # Y holds lists of lists of (38) biniary numbers, only 1 of them is 1.
        
    return (pad_sequences(X, maxlen=max_story_len), pad_sequences(Xq, maxlen=max_question_len), np.array(Y))

In [290]:
# Create our own list of list of word indicies with padding.
def vectorize_stories(data, word_index=tokenizer.word_index, max_story_len=max_story_len, max_question_len=max_question_len):
    # Stories = X
    X = []
    
    # Questions = Xq
    Xq = []
    
    # Y Correct Answer ['yes', 'no']
    Y = []
    for story, query, answer in data:
        
        # for each story
        # [23, 14, 15]
        x = [word_index[word.lower()] for word in story]
        xq = [word_index[word.lower()] for word in query]
        
        y = np.zeros(len(word_index)+1)
        y[word_index[answer]] = 1
        
        X.append(x)   # X holds list of lists of word indices for stories.
        Xq.append(xq) # Xq holds list of lists for word indices for questions.
        Y.append(y) # Y holds lists of lists of (38) biniary numbers, only 1 of them is 1.
        
    return (pad_sequences(X, maxlen=max_story_len), pad_sequences(Xq, maxlen=max_question_len), np.array(Y))

In [318]:
inputs_train, queries_train, answers_train = vectorize_stories(train_data,word_index)

In [320]:
inputs_test, queries_test, answers_test = vectorize_stories(test_data,word_index)

In [322]:
inputs_test

array([[0, 0, 0, ..., 4, 0, 0],
       [0, 0, 0, ..., 4, 0, 0],
       [0, 0, 0, ..., 4, 0, 0],
       ...,
       [0, 0, 0, ..., 4, 0, 0],
       [0, 0, 0, ..., 4, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [324]:
inputs_train

array([[ 0,  0,  0, ...,  4,  0,  0],
       [ 0,  0,  0, ...,  4,  0,  0],
       [ 0,  0,  0, ...,  4,  0,  0],
       ...,
       [ 0,  0,  0, ...,  4,  0,  0],
       [ 0,  0,  0, ..., 11,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [326]:
answers_test

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [328]:
tokenizer.word_index['yes']

KeyError: 'yes'

In [330]:
tokenizer.word_index['no']

KeyError: 'no'

In [314]:
# 497 of the questions have answer 'yes', 503 of the questions have answer 'no'.
sum(answers_test)

array([1000.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.])